### PR TITLE
[FIX] resource_booking: free meetings by default

### PR DESCRIPTION
**Pull request by yajo**
If I'm creating bookings for my colleagues, I'll be the owner of all of the meetings. But that doesn't mean I'll be attending. And OTOH, if I'm part of the bookied resource combination, I'll already be busy due to my attendance status.

So it makes sense to be free by default. However, if I still choose to be busy at that time, I'll create an unavailability as expected.

@Tecnativa TT32666

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
So if I'm part of the booked resources, it will appear as busy?

**Comment by yajo** [comment]
No, but you'll be a confirmed attendee, so your slot will still be unavailable.

**Comment by pedrobaeza** [comment]
But I want that in my agenda it appears as busy, that has nothing to do with the resource booking system.

**Comment by pedrobaeza** [comment]
Can't you do this only if the owner is not attending?

**Comment by yajo** [comment]
Makes sense, changed.

**Comment by yajo** [comment]
All attended, so merging.

/ocabot merge patch

**Pull request merged**
