### PR TITLE
[15.0][IMP] resource_booking: New activity type for resource booking

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
Add new activity type "Resource booking", and when chosen, it takes us to a draft resource booking, where we can define the necessary data. When the appointment is agreed, then the system will create the mail.activity linked to the calendar event generated the reservation booking.

@Tecnativa
TT47152

@pedrobaeza @pilarvargas-tecnativa

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Several comments after trying on runboat:

- The mail activity can be created in a day far in the future while the resource booking (RB) is not yet scheduled. 
- Once the RB is scheduled, the date of the activity should be synchronized.
- If the RB is cancelled, the activity should be removed.

**Comment by carolinafernandez-tecnativa** [comment]
> Several comments after trying on runboat:
> 
> * The mail activity can be created in a day far in the future while the resource booking (RB) is not yet scheduled.
> * Once the RB is scheduled, the date of the activity should be synchronized.
> * If the RB is cancelled, the activity should be removed.

Hi @pedrobaeza , I have checked your comments.

See this example:

1- Created Resource booking for tomorrow for this contact (2024-01-17):

image

2- Change start date for Resource booking to 2024-01-18

image

3- Go to the activity and date is updated:

image

4- Go to Resource booking and cancel it, activity dissapears:

image

image

image

**Comment by pedrobaeza** [comment]
Try the same without putting immediately the scheduled date on the resource booking, but saving it in "draft" state (you have to go to list view instead of the calendar one). You will see that once you schedule it, the activity is not correctly "rescheduled". And please read the rest of my comment.

**Comment by pedrobaeza** [comment]
Some fine-tuning still pending:

- The default view when going to resource booking may it be the form view creating the resource booking directly.
- Once the date has been scheduled, the linked activity should be updated with the proper deadline.

@victoralmau can you resume this work to finish this?

**Comment by victoralmau** [comment]
Changes done.

**Comment by pedrobaeza** [comment]
After scheduling (in 2 steps) the resource booking in http://oca-calendar-15-0-pr114-a7a1af9762b1.runboat.odoo-community.org, it still puts the incorrect deadline:

imagen

And another thing: please add "Re-schedule" button in the activity the same as in meetings.

**Comment by victoralmau** [comment]
Changes done.

**Review by pedrobaeza — APPROVED** [review]
Now it's working properly. Thanks for the extra feature.

/ocabot merge major

**Pull request merged**
