### PR TITLE
[FIX] resource_booking: autosubscribe resource partners

### PR DESCRIPTION
**Pull request by yajo**
When some partner is a resource assigned to a booking, he should get auto-subscribed.

Inspired in https://github.com/OCA/calendar/pull/42, but I'm changing that behavior.

@Tecnativa TT32148

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by joao-p-marques — APPROVED** [review]
Code review :+1:

**Comment by pedrobaeza** [comment]
Does some of this be forward-ported?

**Comment by joao-p-marques** [comment]
I believe so, but @Yajo is already on it...

**Comment by yajo** [comment]
Yes, will do after fixing a regression introduced.

**Pull request merged**
