### PR TITLE
[16.0][IMP] resource_booking: Reduce and simplify code according to https://github.com/odoo/odoo/pull/174494/commits/d7bbcefd4002dda07e06b89b4bc69b80c8e338fd

### PR DESCRIPTION
**Pull request by victoralmau**
Reduce and simplify code according to https://github.com/odoo/odoo/pull/174494/commits/d7bbcefd4002dda07e06b89b4bc69b80c8e338fd

The changes added at https://github.com/OCA/calendar/commit/851dc9a6bba7a0241857ce15312a5edbee1e6b5d and https://github.com/OCA/calendar/commit/a3cd5a883b809237150e0da3247f68f02f4b4c4c are unnecessary according to the approach added at https://github.com/odoo/odoo/pull/174494/commits/d7bbcefd4002dda07e06b89b4bc69b80c8e338fd. We maintain the tests to confirm that the expected behavior is maintained.

Please @pedrobaeza and @sergio-teruel can you review it?

 @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
This must be merged, as now tests are broken:

/ocabot merge patch

**Comment by pedrobaeza** [comment]
@victoralmau can you check the failing?

**Comment by victoralmau** [comment]
https://github.com/OCA/pos/issues/1236

**Pull request merged**
