### PR TITLE
[FIX] resource_booking: multicompany access

### PR DESCRIPTION
**Pull request by yajo**
Without this patch, users can list but not read resource bookings that belong to a type of an alien company.

@Tecnativa TT31445

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Fast-tracking obvious bug:

/ocabot merge minor

Please fw-port it to v13 (with migration script required)

**Comment by pedrobaeza** [comment]
@Yajo please don't self merge things.

**Comment by yajo** [comment]
Don't worry, I'm maintainer. :)

**Pull request merged**
