### PR TITLE
[FIX] notes field visibility and italian translations

### PR DESCRIPTION
**Pull request by SimoRubi**
minor view fix and italian translations

### CODE REVIEW

**Comment by SimoRubi** [comment]
@tafaRU could you please check?

**Comment by tafaRU** [comment]
@SimoRubi, concerning translation it should be better to use Transifex.

**Comment by SimoRubi** [comment]
@tafaRU I can't find this module in transifex, maybe the repo needs some configuration?

**Review by dreispt — APPROVED** [review]

**Comment by SimoRubi** [comment]
@tafaRU please configure the repo in order to add translations in transifex, so I can move the translations in there

**Comment by tafaRU** [comment]
> please configure the repo in order to add translations in transifex, so I can move the translations in there

I don't know how to do this so you get my :+1:

**Review by tafaRU — APPROVED** [review]

**Pull request merged**
