### PR TITLE
[16.0][ADD] calendar_monthly_multi: Calendar monthly extension

### PR DESCRIPTION
**Pull request by tarteo**
This module extends the functionality of monthly recurring events in the calendar:

1. **Multiple dates**: For example every 5th and 15th of the month
2. **All days, Weekday (monday to friday), weekend days (saturday and sunday) or
   custom**: For example The first weekday of the month

multiple-dates

weekday-weekendday

### CODE REVIEW

**Comment by OpenCode** [comment]
@tarteo Can you remove "fixup" strings from the commit body, please?

**Comment by tarteo** [comment]
@OpenCode Hey man, sorry for the super late response but I removed it :wink:

**Comment by OpenCode** [comment]
> @OpenCode Hey man, sorry for the super late response but I removed it 😉

Don't worry. Take your time 🤣

There are red tests.

**Comment by tarteo** [comment]
@OpenCode Hmmm, something has changed in Odoo why my tests are not green anymore. I pin pointed it to this commit: https://github.com/odoo/odoo/commit/43a774d68574e72fa4aabad65db42a03fac6e666#diff-6c4c124bfb9e4397bed7221c7534c8f877904775e9db4cf81f72b5430b36ad06R631
Also the way the name of a recurrence is created it changed but I'll leave my code as is for that part

I'll let you know when I fixed it

**Comment by tarteo** [comment]
@OpenCode fixed the tests :tada:

**Comment by OpenCode** [comment]
> @OpenCode fixed the tests 🎉

Can you squash the commits in the first one?

**Comment by tarteo** [comment]
@OpenCode :heavy_check_mark:

**Review by OpenCode — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Quick code review, but being a new module and coming from a trusted contributor, I think it's enough. 

/ocabot merge nobump

**Pull request merged**
