### PR TITLE
[14.0] Migrate: resource_booking

### PR DESCRIPTION
**Pull request by njeudy**
I just migrate this wonderfull module to V14 (ecommerce, survey and sale are coming)

WIP: adapt tests

### CODE REVIEW

**Comment by njeudy** [comment]
@Yajo @pedrobaeza  can you drive me if I need to clean commit history ok keep it like this ?

**Comment by yajo** [comment]
AFAICS the history is just what we had in OCA already, so nothing to change.

Make sure you're migrating from v13, where the module is better (I think you are, just a reminder).

Also please do some explanations about the things you're changing, as they seem related to deep changes in the calendar app. I think a little explanation will help reviewing them.

Oh, and travis went ❌ 

Thanks!

**Comment by manuelcalerosolis** [comment]
@njeudy please review the code, test is falling in Travis.

**Comment by marcos-mendez** [comment]
I think it is failing in several parts, maybe it hasn't been completly migrated. Maybe i can help in something @njeudy  ?

**Comment by pedrobaeza** [comment]
@njeudy, FYI, I'm going to finally migrate this module to 14.0, so I will supersede this PR and release you from doing it. The rest of the modules we talked about in OCA days won't be migrated to 14.0 though, but they should be easier to migrate.

**Comment by pedrobaeza** [comment]
Superseded by #73

**Pull request closed without merging**
