### PR TITLE
[12.0] add calendar base booking

### PR DESCRIPTION
**Pull request by sebastienbeau**
Work in progress
The aim of this module is to add an abstract mixing for managing booking.
This can be added on every odoo model.
We build this dependency in order to had the feature of booking a datetime for retrieving the delivery into a physical shop (for Shopinvader), more module to come.

### CODE REVIEW

**Comment by cubells** [comment]
hi @sebastienbeau 
if you need help on this give a ping.

**Comment by sebastienbeau** [comment]
Thanks for proposing
I am going to rework on this next week and the week after (we deliverer in production the version 8 for the customer and new we can go back on v12 so it will be ready when we migrate the customer)
I plan to do some refactoring so we can reuse the feature in different context (renting, manufacturing...)
I will ping you for a review

**Comment by sebastienbeau** [comment]
Hi just for information, I have some priority change.
So for now I will not work on it before september.
But it's still on my planning

**Comment by sebastienbeau** [comment]
Closed in favours of https://github.com/OCA/calendar/pull/20 in V14

**Pull request closed without merging**
